#!bin/bash
# Default all to DROP
# SSH Open

echo -------------------------------
echo Starting IPTABLES Configuration

# Flush All
iptables --flush

# Loopback i/o
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# SSH i/o
iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j OUTPUT
iptables -A INPUT -m state --state ESTABLISHED,RELATED -j OUTPUT

# All Others Blocked
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP

echo Finished IPTABLES Configuration
echo -------------------------------
echo Making Configuration Persistent

# Make Persistent
iptables-save >/etc/iptables/rules.v4
ip6tables-save >/etc/iptables/rules.v6

echo Configuration is Persistent
echo ---------------------------
echo Script Completed
echo ':)'
